# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("智能家庭安防系统")
        MainWindow.resize(800, 1200)  # 增加窗口高度
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Logo显示区域
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(250, 30, 300, 100))  # 调整Y坐标
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setText("智能家庭安防系统")
        self.logo.setStyleSheet("font-size: 32px; font-weight: bold; color: #E8F5E9;")
        
        # 主要控制按钮区域
        self.button_widget = QtWidgets.QWidget(self.centralwidget)
        self.button_widget.setGeometry(QtCore.QRect(100, 160, 600, 80))  # 增加高度，调整Y坐标
        self.button_layout = QtWidgets.QHBoxLayout(self.button_widget)
        self.button_layout.setSpacing(30)  # 增加按钮间距
        
        # 设置按钮样式和尺寸
        button_style = """
            QPushButton {
                background-color: #E8F5E9;
                color: #263238;
                border-radius: 10px;
                padding: 15px;
                font-weight: bold;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #C8E6C9;
            }
        """
        
        # 摄像头控制按钮
        self.camera_button = QtWidgets.QPushButton(self.button_widget)
        self.camera_button.setMinimumSize(120, 60)  # 增加按钮尺寸
        self.camera_button.setStyleSheet(button_style)
        self.camera_button.setObjectName("camera_button")
        
        # 检测控制按钮
        self.detect_button = QtWidgets.QPushButton(self.button_widget)
        self.detect_button.setMinimumSize(120, 60)  # 增加按钮尺寸
        self.detect_button.setStyleSheet(button_style)
        self.detect_button.setObjectName("detect_button")
        
        # 警报控制按钮
        self.alert_ignore = QtWidgets.QPushButton(self.button_widget)
        self.alert_ignore.setMinimumSize(120, 60)  # 增加按钮尺寸
        self.alert_ignore.setStyleSheet(button_style)
        self.alert_ignore.setObjectName("alert_ignore")
        self.alert_ignore.setText("开启警报")
        
        # 添加按钮到布局
        self.button_layout.addWidget(self.camera_button)
        self.button_layout.addWidget(self.detect_button)
        self.button_layout.addWidget(self.alert_ignore)
        
        # 目录设置区域
        self.dir_group = QtWidgets.QGroupBox(self.centralwidget)
        self.dir_group.setGeometry(QtCore.QRect(100, 270, 600, 120))  # 调整Y坐标和高度
        self.dir_group.setTitle("存储目录设置")
        self.dir_group.setStyleSheet("""
            QGroupBox {
                font-weight: bold;
                color: #E8F5E9;
                font-size: 14px;
            }
        """)
        
        # 使用网格布局来排列目录设置
        self.dir_layout = QtWidgets.QGridLayout(self.dir_group)
        self.dir_layout.setVerticalSpacing(20)  # 增加垂直间距
        
        # 录制目录设置
        self.record_dir_label = QtWidgets.QLabel(self.dir_group)
        self.record_dir_label.setText("录制目录：")
        self.record_dir_label.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        self.record_dir_path = QtWidgets.QLineEdit(self.dir_group)
        self.record_dir_path.setMinimumHeight(30)  # 增加输入框高度
        self.record_dir_button = QtWidgets.QPushButton("选择", self.dir_group)
        self.record_dir_button.setMinimumSize(60, 30)  # 调整选择按钮尺寸
        self.record_dir_button.setStyleSheet(button_style)
        
        # 截图目录设置
        self.snapshot_dir_label = QtWidgets.QLabel(self.dir_group)
        self.snapshot_dir_label.setText("截图目录：")
        self.snapshot_dir_label.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        self.snapshot_dir_path = QtWidgets.QLineEdit(self.dir_group)
        self.snapshot_dir_path.setMinimumHeight(30)  # 增加输入框高度
        self.snapshot_dir_button = QtWidgets.QPushButton("选择", self.dir_group)
        self.snapshot_dir_button.setMinimumSize(60, 30)  # 调整选择按钮尺寸
        self.snapshot_dir_button.setStyleSheet(button_style)
        
        # 添加到网格布局
        self.dir_layout.addWidget(self.record_dir_label, 0, 0)
        self.dir_layout.addWidget(self.record_dir_path, 0, 1)
        self.dir_layout.addWidget(self.record_dir_button, 0, 2)
        self.dir_layout.addWidget(self.snapshot_dir_label, 1, 0)
        self.dir_layout.addWidget(self.snapshot_dir_path, 1, 1)
        self.dir_layout.addWidget(self.snapshot_dir_button, 1, 2)
        
        # 阈值设置区域
        self.settings_group = QtWidgets.QGroupBox(self.centralwidget)
        self.settings_group.setGeometry(QtCore.QRect(100, 420, 600, 140))  # 调整Y坐标和高度
        self.settings_group.setTitle("检测阈值设置")
        self.settings_group.setStyleSheet("""
            QGroupBox {
                font-weight: bold;
                color: #E8F5E9;
                font-size: 14px;
            }
        """)
        
        # 使用网格布局来排列阈值设置
        self.settings_layout = QtWidgets.QGridLayout(self.settings_group)
        self.settings_layout.setVerticalSpacing(20)  # 增加垂直间距
        
        # 火灾检测阈值
        self.fire_label_threshold = QtWidgets.QLabel(self.settings_group)
        self.fire_label_threshold.setText("火灾检测阈值：")
        self.fire_label_threshold.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        self.fire_threshold = QtWidgets.QSlider(QtCore.Qt.Horizontal, self.settings_group)
        self.fire_threshold.setMinimumHeight(30)  # 增加滑块高度
        self.fire_threshold.setMinimum(10)
        self.fire_threshold.setMaximum(90)
        self.fire_threshold.setValue(60)
        self.fire_value_label = QtWidgets.QLabel("0.6", self.settings_group)
        self.fire_value_label.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        
        # 人脸识别阈值
        self.label_threshold = QtWidgets.QLabel(self.settings_group)
        self.label_threshold.setText("人脸识别阈值：")
        self.label_threshold.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        self.face_threshold = QtWidgets.QSlider(QtCore.Qt.Horizontal, self.settings_group)
        self.face_threshold.setMinimumHeight(30)  # 增加滑块高度
        self.face_threshold.setMinimum(10)
        self.face_threshold.setMaximum(90)
        self.face_threshold.setValue(80)
        self.face_value_label = QtWidgets.QLabel("0.8", self.settings_group)
        self.face_value_label.setStyleSheet("color: #E8F5E9; font-size: 14px;")
        
        # 添加到网格布局
        self.settings_layout.addWidget(self.fire_label_threshold, 0, 0)
        self.settings_layout.addWidget(self.fire_threshold, 0, 1)
        self.settings_layout.addWidget(self.fire_value_label, 0, 2)
        self.settings_layout.addWidget(self.label_threshold, 1, 0)
        self.settings_layout.addWidget(self.face_threshold, 1, 1)
        self.settings_layout.addWidget(self.face_value_label, 1, 2)
        
        # 警报指示灯区域
        self.alert_indicators = QtWidgets.QGroupBox(self.centralwidget)
        self.alert_indicators.setGeometry(QtCore.QRect(100, 590, 600, 100))  # 调整Y坐标和高度
        self.alert_indicators.setTitle("警报状态")
        self.alert_indicators.setStyleSheet("""
            QGroupBox {
                font-weight: bold;
                color: #E8F5E9;
                font-size: 14px;
            }
        """)
        
        # 使用水平布局
        self.indicators_layout = QtWidgets.QHBoxLayout(self.alert_indicators)
        self.indicators_layout.setSpacing(40)
        
        # 警报指示灯样式
        indicator_style = """
            QLabel {
                background-color: #37474F;
                color: #E8F5E9;
                border: 2px solid #E8F5E9;
                border-radius: 15px;
                padding: 15px;
                min-width: 120px;
                font-size: 14px;
                text-align: center;
            }
        """
        
        # 火灾指示灯
        self.fire_indicator = QtWidgets.QLabel("火灾")
        self.fire_indicator.setStyleSheet(indicator_style)
        self.fire_indicator.setAlignment(QtCore.Qt.AlignCenter)
        
        # 烟雾指示灯
        self.smoke_indicator = QtWidgets.QLabel("烟雾")
        self.smoke_indicator.setStyleSheet(indicator_style)
        self.smoke_indicator.setAlignment(QtCore.Qt.AlignCenter)
        
        # 陌生人指示灯
        self.stranger_indicator = QtWidgets.QLabel("陌生人")
        self.stranger_indicator.setStyleSheet(indicator_style)
        self.stranger_indicator.setAlignment(QtCore.Qt.AlignCenter)
        
        # 添加指示灯到布局
        self.indicators_layout.addWidget(self.fire_indicator)
        self.indicators_layout.addWidget(self.smoke_indicator)
        self.indicators_layout.addWidget(self.stranger_indicator)
        
        # 视频显示区域
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(100, 720, 600, 400))  # 调整Y坐标
        self.screen.setStyleSheet("""
            QLabel {
                border: 2px solid #E8F5E9;
                border-radius: 5px;
                color: #E8F5E9;
                font-size: 14px;
            }
        """)
        self.screen.setAlignment(QtCore.Qt.AlignCenter)
        self.screen.setText("等待摄像头画面")
        self.screen.setObjectName("screen")
        
        # 状态显示区域
        self.status_group = QtWidgets.QGroupBox(self.centralwidget)
        self.status_group.setGeometry(QtCore.QRect(100, 1150, 600, 150))  # 调整Y坐标
        self.status_group.setTitle("状态信息")
        self.status_group.setStyleSheet("""
            QGroupBox {
                font-weight: bold;
                color: #E8F5E9;
                font-size: 14px;
            }
        """)
        
        self.status_text = QtWidgets.QTextEdit(self.status_group)
        self.status_text.setGeometry(QtCore.QRect(10, 30, 580, 110))
        self.status_text.setReadOnly(True)
        
        # 设置整体样式
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #263238;
            }
            QLineEdit {
                padding: 5px;
                border: 1px solid #E8F5E9;
                border-radius: 5px;
                background-color: #37474F;
                color: #E8F5E9;
                font-size: 14px;
            }
            QTextEdit {
                border: 1px solid #E8F5E9;
                border-radius: 5px;
                background-color: #37474F;
                color: #E8F5E9;
                font-size: 14px;
            }
            QSlider::groove:horizontal {
                border: 1px solid #E8F5E9;
                height: 10px;
                background: #37474F;
                margin: 2px 0;
                border-radius: 5px;
            }
            QSlider::handle:horizontal {
                background: #E8F5E9;
                border: 1px solid #E8F5E9;
                width: 20px;
                margin: -5px 0;
                border-radius: 10px;
            }
            QSlider::handle:horizontal:hover {
                background: #C8E6C9;
            }
        """)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能家庭安防系统"))
        self.camera_button.setText(_translate("MainWindow", "打开摄像头"))
        self.detect_button.setText(_translate("MainWindow", "开始检测"))
